import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { FaMessage } from "react-icons/fa6";
import { FaUsersRectangle } from "react-icons/fa6";
import { FaCircleUser } from "react-icons/fa6";
import { MdHome } from "react-icons/md";
import { MdLogout } from "react-icons/md";
import { TbSocial } from "react-icons/tb";
import Link from "next/link";
import { userAuth } from "./components/auths/auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="flex items-center bg-slate-50 fixed top-0 left-0 right-0 w-full z-[100] shadow gap-5 bg-white p-2 py-[20px] px-[30px] overflow-x-hidden justify-between">
          <div className="flex items-center gap-3">
          <div className="flex items-center  text-white py-[5px] px-[10px] rounded">
          <TbSocial className="md:text-[50px] text-[25px] text-blue-500"/>
          <h1 className="md:text-[15px] text-[12px] text-blue-500 ">MYsocial</h1>
            </div>
            <input type="text" className="bg-slate-50 rounded capitalize outline-none py-[18px] w-full md:block hidden  text-center text-[15px]" placeholder="search for a post here" name="" id="" />
     </div>
          <div className="flex items-center gap-5 ">
          <Link href="/" className="flex flex-col items-center gap-0">
              <MdHome className="text-slate-700 text-[15px] md:text-[20px]"/>
              <span className="md:text-[12px] text-[10px] ">Home</span>
            </Link>
            <Link href="/chat" className="flex flex-col items-center gap-0">
              <FaMessage className="text-slate-700  text-[15px] md:text-[20px]"/>
              <span className="md:text-[12px] text-[10px]">Messaging</span>
            </Link>
            <Link href="/users" className="flex flex-col items-center gap-0">
              <FaUsersRectangle className="text-slate-700  text-[15px] md:text-[20px]"/>
              <span className="md:text-[12px] text-[10px]">Friends</span>
            </Link>
            <Link href="/my-profile" className="flex flex-col items-center gap-0">
              <FaCircleUser className="text-slate-700  text-[15px] md:text-[20px]"/>
              <span className="md:text-[12px] text-[10px]">Me</span>
            </Link>
          </div>
    </header>
        {children}
      </body>
      <ToastContainer autoClose={2000} />
    </html>
  );
}