import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { FaMessage } from "react-icons/fa6";
import { FaUsersRectangle } from "react-icons/fa6";
import { FaCircleUser } from "react-icons/fa6";
import { MdHome } from "react-icons/md";
import { MdLogout } from "react-icons/md";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>{children}</body>
      <ToastContainer autoClose={2000} />
    </html>
  );
}