import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { FaMessage } from "react-icons/fa6";
import { FaUsersRectangle } from "react-icons/fa6";
import { FaCircleUser } from "react-icons/fa6";
import { MdHome } from "react-icons/md";
import { MdLogout } from "react-icons/md";
import { TbSocial } from "react-icons/tb";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="flex items-center bg-slate-50 fixed top-0 left-0 right-0 w-full z-[100] shadow gap-5 bg-white p-2 px-[30px] justify-between">
      <div className="flex items-center bg-blue-500 text-white py-[5px] px-[10px] rounded">
          <TbSocial className="text-[50px]"/>
          <h1 className="text-[15px] ">MYsocial</h1>
          </div>
          <input type="text" className="bg-slate-50 rounded capitalize outline-none py-[18px] w-full md:block hidden  text-center text-[15px]" placeholder="search for a post here" name="" id="" />
          <div className="flex items-center gap-5 ">
          <Link href="" className="flex flex-col items-center gap-0">
              <MdHome className="text-slate-700 text-[20px]"/>
              <span className="text-[12px]">Home</span>
            </Link>
            <Link href="" className="flex flex-col items-center gap-0">
              <FaMessage className="text-slate-700 text-[20px]"/>
              <span className="text-[12px]">Messaging</span>
            </Link>
            <Link href="" className="flex flex-col items-center gap-0">
              <FaUsersRectangle className="text-slate-700 text-[20px]"/>
              <span className="text-[12px]">Friends</span>
            </Link>
            <Link href="" className="flex flex-col items-center gap-0">
              <FaCircleUser className="text-slate-700 text-[20px]"/>
              <span className="text-[12px]">Me</span>
            </Link>
          </div>
    </header>
        {children}
      </body>
      <ToastContainer autoClose={2000} />
    </html>
  );
}